package br.com.financepro.financePro.payment.enums;

public enum PaymentStatusDetail {
    ACCREDITED,
    PENDING_REVIEW,
    PENDING_WAITING_PAYMENT,
    PENDING_CONTINGENCY,
    REJECTED_HIGH_RISK,
    REJECTED_INVALID_INSTALLMENTS,
    REJECTED_INVALID_CARD,
    REJECTED_INSUFFICIENT_AMOUNT,
    REJECTED_CALL_FOR_AUTHORIZE,
    REJECTED_OTHER_REASON,
    REFUNDED,
    CHARGED_BACK
}